// Course data
const COURSES = [
  {
    id: 'cs101',
    title: 'Full-Stack Web Development',
    category: 'tech',
    description: 'Master React, Node.js, databases, and deployment. Build production-ready web applications from scratch.',
    duration: '16 weeks',
    level: 'Intermediate',
    maxStudents: 30,
  },
  {
    id: 'cs102',
    title: 'Machine Learning & AI',
    category: 'data',
    description: 'Explore neural networks, deep learning, NLP, and computer vision using Python and TensorFlow.',
    duration: '20 weeks',
    level: 'Advanced',
    maxStudents: 25,
  },
  {
    id: 'cs103',
    title: 'Cybersecurity Fundamentals',
    category: 'tech',
    description: 'Learn ethical hacking, network security, cryptography, and vulnerability assessment techniques.',
    duration: '12 weeks',
    level: 'Beginner',
    maxStudents: 35,
  },
  {
    id: 'ds201',
    title: 'Data Science with Python',
    category: 'data',
    description: 'Analyze real-world datasets using pandas, NumPy, matplotlib, and statistical modeling.',
    duration: '14 weeks',
    level: 'Intermediate',
    maxStudents: 30,
  },
  {
    id: 'cr301',
    title: 'UX/UI Design Mastery',
    category: 'creative',
    description: 'Design intuitive user experiences with Figma, design systems, prototyping, and user research.',
    duration: '10 weeks',
    level: 'Beginner',
    maxStudents: 25,
  },
  {
    id: 'cr302',
    title: '3D Animation & Motion Graphics',
    category: 'creative',
    description: 'Create stunning 3D animations using Blender, After Effects, and motion design principles.',
    duration: '18 weeks',
    level: 'Intermediate',
    maxStudents: 20,
  },
  {
    id: 'bs401',
    title: 'Digital Marketing Strategy',
    category: 'business',
    description: 'Master SEO, social media marketing, content strategy, analytics, and paid advertising.',
    duration: '8 weeks',
    level: 'Beginner',
    maxStudents: 40,
  },
  {
    id: 'bs402',
    title: 'Product Management',
    category: 'business',
    description: 'Learn agile methodologies, roadmap planning, stakeholder management, and product-led growth.',
    duration: '12 weeks',
    level: 'Intermediate',
    maxStudents: 30,
  },
  {
    id: 'sc501',
    title: 'Blockchain & Web3 Development',
    category: 'tech',
    description: 'Build decentralized apps with Solidity, smart contracts, and blockchain architecture.',
    duration: '14 weeks',
    level: 'Advanced',
    maxStudents: 20,
  },
  {
    id: 'sc502',
    title: 'Cloud Architecture (AWS)',
    category: 'tech',
    description: 'Design scalable cloud solutions with AWS services, serverless computing, and DevOps practices.',
    duration: '16 weeks',
    level: 'Intermediate',
    maxStudents: 30,
  },
  {
    id: 'cr303',
    title: 'Game Development with Unity',
    category: 'creative',
    description: 'Create 2D and 3D games using Unity, C#, game physics, and interactive storytelling.',
    duration: '20 weeks',
    level: 'Intermediate',
    maxStudents: 25,
  },
  {
    id: 'sc503',
    title: 'Quantum Computing Basics',
    category: 'science',
    description: 'Introduction to quantum mechanics principles, qubits, quantum gates, and quantum algorithms.',
    duration: '10 weeks',
    level: 'Advanced',
    maxStudents: 15,
  },
];

// Pre-populated students
const INITIAL_STUDENTS = [
  { id: 1, name: 'Emma Johnson', email: 'emma.johnson@mail.com', enrolledCourses: ['cs101', 'cr301'] },
  { id: 2, name: 'Liam Chen', email: 'liam.chen@mail.com', enrolledCourses: ['cs102', 'ds201'] },
  { id: 3, name: 'Sofia Martinez', email: 'sofia.m@mail.com', enrolledCourses: ['cr301', 'cr302', 'bs401'] },
  { id: 4, name: 'Noah Williams', email: 'noah.w@mail.com', enrolledCourses: ['cs101', 'sc502'] },
  { id: 5, name: 'Ava Patel', email: 'ava.patel@mail.com', enrolledCourses: ['bs401', 'bs402', 'cs103'] },
  { id: 6, name: 'Ethan Kim', email: 'ethan.k@mail.com', enrolledCourses: ['cs102', 'sc501', 'sc503'] },
];

// Avatar color palette
const AVATAR_COLORS = [
  '#FF6B6B', '#4ECDC4', '#45B7D1', '#96CEB4',
  '#FFEAA7', '#DDA0DD', '#98D8C8', '#F7DC6F',
  '#BB8FCE', '#85C1E9', '#F0B27A', '#82E0AA',
  '#F1948A', '#AED6F1', '#D7BDE2', '#A3E4D7',
];

export { COURSES, AVATAR_COLORS, INITIAL_STUDENTS };
